export type ProjectCoverShape = 'portrait' | 'square' | 'landscape';

export interface Project {
  readonly id: string;
  readonly title: string;
  readonly category: string;
  readonly year: string;
  readonly brand: string;
  readonly image: string;
  readonly alt: string;
  readonly width: number;
  readonly height: number;
  readonly shape?: ProjectCoverShape;
  readonly featured: boolean;
}

// A data-source boundary: future project records can use the same featured selection.
export function getFeaturedProjects(
  projects: readonly Project[],
): readonly Project[] {
  return projects.filter((project) => project.featured);
}

// Working preview records. Years are sample values; concept entries are not client work.
export const homeProjects = [
  {
    id: 'penvo-identity',
    title: 'Made to be recognised',
    category: 'Brand identity',
    year: '2026',
    brand: 'Penvo',
    image: '/projects/penvo-identity.webp',
    alt: 'Close-up of an orange hoodie with the white Penvo logo.',
    width: 1484,
    height: 1060,
    shape: 'square',
    featured: true,
  },
  {
    id: 'penvo-digital',
    title: 'Penvo in your pocket',
    category: 'Digital brand concept',
    year: '2026',
    brand: 'Penvo',
    image: '/projects/penvo-digital.webp',
    alt: 'Close-up of a smartphone home screen with an orange Penvo app icon.',
    width: 1000,
    height: 1344,
    shape: 'portrait',
    featured: true,
  },
  {
    id: 'wellness-digital',
    title: 'Room to breathe',
    category: 'Web design concept',
    year: '2026',
    brand: 'Wellness concept',
    image: '/projects/wellness-digital.webp',
    alt: 'Desktop monitor showing a botanical website concept in a sunlit workspace.',
    width: 1536,
    height: 1024,
    shape: 'landscape',
    featured: true,
  },
  {
    id: 'paper-and-print',
    title: 'Identity, on paper',
    category: 'Brand & print concept',
    year: '2026',
    brand: 'Stationery concept',
    image: '/projects/paper-and-print.webp',
    alt: 'Textured stationery and business cards with black and orange geometric graphics.',
    width: 1536,
    height: 1024,
    shape: 'square',
    featured: true,
  },
  {
    id: 'packaging-concept',
    title: 'Form meets feeling',
    category: 'Packaging design concept',
    year: '2026',
    brand: 'Packaging concept',
    image: '/projects/packaging-concept.webp',
    alt: 'Amber bottle and cream cartons with orange and black circular graphics.',
    width: 1536,
    height: 1024,
    shape: 'portrait',
    featured: true,
  },
  {
    id: 'campaign-concept',
    title: 'Made for the outdoors',
    category: 'Campaign art direction concept',
    year: '2026',
    brand: 'Outdoor concept',
    image: '/projects/campaign-concept.webp',
    alt: 'Person in an orange rain jacket hiking through a green forest beside a waterfall.',
    width: 1536,
    height: 1024,
    shape: 'portrait',
    featured: true,
  },
  {
    id: 'editorial-concept',
    title: 'Stories worth keeping',
    category: 'Editorial design concept',
    year: '2026',
    brand: 'Journal concept',
    image: '/projects/editorial-concept.svg',
    alt: 'Graphic journal cover with bold typography and the Penvo monogram.',
    width: 1200,
    height: 900,
    shape: 'square',
    featured: true,
  },
  {
    id: 'social-concept',
    title: 'Built to stand out',
    category: 'Social campaign concept',
    year: '2026',
    brand: 'Campaign concept',
    image: '/projects/social-concept.svg',
    alt: 'Orange and black social campaign artwork with bold graphic typography.',
    width: 1200,
    height: 900,
    shape: 'landscape',
    featured: true,
  },
  {
    id: 'retail-concept',
    title: 'A place with presence',
    category: 'Retail identity concept',
    year: '2026',
    brand: 'Retail concept',
    image: '/projects/retail-concept.svg',
    alt: 'Illustrated storefront with orange signage and a branded window.',
    width: 1200,
    height: 900,
    shape: 'landscape',
    featured: true,
  },
  {
    id: 'merch-concept',
    title: 'Carry the identity',
    category: 'Merchandise design concept',
    year: '2026',
    brand: 'Merch concept',
    image: '/projects/merch-concept.svg',
    alt: 'Illustrated tote bag carrying the Penvo monogram and graphic identity.',
    width: 1200,
    height: 900,
    shape: 'square',
    featured: true,
  },
  {
    id: 'dashboard-concept',
    title: 'Clarity in every click',
    category: 'Product design concept',
    year: '2026',
    brand: 'Dashboard concept',
    image: '/projects/dashboard-concept.svg',
    alt: 'Analytics dashboard concept with charts, metric cards, and orange accents.',
    width: 1200,
    height: 900,
    shape: 'landscape',
    featured: true,
  },
  {
    id: 'event-concept',
    title: 'An event to remember',
    category: 'Event identity concept',
    year: '2026',
    brand: 'Event concept',
    image: '/projects/event-concept.svg',
    alt: 'Black and orange event ticket and identity artwork with the Penvo mark.',
    width: 1200,
    height: 900,
    shape: 'square',
    featured: true,
  },
  {
    id: 'coffee-concept',
    title: 'A better daily ritual',
    category: 'Packaging design concept',
    year: '2026',
    brand: 'Coffee concept',
    image: '/projects/coffee-concept.svg',
    alt: 'Illustrated coffee packaging with orange labels and geometric graphics.',
    width: 1200,
    height: 900,
    shape: 'landscape',
    featured: true,
  },
  {
    id: 'wayfinding-concept',
    title: 'Find your next move',
    category: 'Wayfinding design concept',
    year: '2026',
    brand: 'Signage concept',
    image: '/projects/wayfinding-concept.svg',
    alt: 'Architectural signage concept with directional arrows and orange panels.',
    width: 1200,
    height: 900,
    shape: 'square',
    featured: true,
  },
] as const satisfies readonly Project[];
